"""Pydantic Schemas for Module 10 Multi-LLM AI Orchestration.

Defines standardized contracts for:
- PatientCase & Data Minimization
- Independent Model Assessment Outputs
- Deterministic Consensus Results
- AI Judge Synthesis
- Safety Engine Evaluation
- Final Consolidated Health Assessment
"""

from typing import List, Optional, Dict, Any, Union
from pydantic import BaseModel, Field, ConfigDict


class PatientCase(BaseModel):
    """Structured clinical intake case representation."""
    main_complaint: str = Field(
        default="",
        description="The primary symptom or medical concern reported by the patient."
    )
    symptoms: List[str] = Field(
        default_factory=list,
        description="List of all reported symptoms."
    )
    duration: Optional[str] = Field(
        default=None,
        description="How long symptoms have lasted (e.g., '1 day', '3 weeks')."
    )
    severity: Optional[Union[int, str]] = Field(
        default=None,
        description="Severity rating, preferably 1-10 or descriptive."
    )
    onset: Optional[str] = Field(
        default="",
        description="Onset characteristics (e.g., 'gradual', 'sudden', 'after exertion')."
    )
    associated_symptoms: List[str] = Field(
        default_factory=list,
        description="Secondary or concurrent symptoms (e.g., nausea, photophobia)."
    )
    medical_conditions: List[str] = Field(
        default_factory=list,
        description="Relevant existing chronic conditions."
    )
    medications: List[str] = Field(
        default_factory=list,
        description="Active medications."
    )
    allergies: List[str] = Field(
        default_factory=list,
        description="Critical known drug or environmental allergies."
    )
    age: Optional[int] = Field(
        default=None,
        description="Patient age in years."
    )
    sex: Optional[str] = Field(
        default=None,
        description="Patient biological sex."
    )
    red_flags: List[str] = Field(
        default_factory=list,
        description="Emergency red-flag symptoms identified."
    )

    model_config = ConfigDict(from_attributes=True)

    def to_minimized_payload(self) -> Dict[str, Any]:
        """Data Minimization (Step 4): Strips all PII (names, emails, tokens, IDs).
        
        Only sends anonymized, relevant clinical facts to external LLMs.
        """
        return {
            "age": self.age if self.age is not None else "Unknown",
            "sex": self.sex if self.sex else "Unknown",
            "main_complaint": self.main_complaint,
            "symptoms": self.symptoms,
            "duration": self.duration or "Not specified",
            "severity": self.severity if self.severity is not None else "Not rated",
            "onset": self.onset or "Not specified",
            "associated_symptoms": self.associated_symptoms,
            "conditions": self.medical_conditions,
            "medications": self.medications,
            "allergies": self.allergies,
            "red_flags": self.red_flags,
        }


class IntakeTurnOutput(BaseModel):
    """Output generated by Gemini Conversational Intake AI on each turn."""
    assistant_message: str = Field(
        ...,
        description="Empathetic, clear clinical response with 1-2 focused questions or intake completion message."
    )
    information_complete: bool = Field(
        default=False,
        description="True if essential intake details have been gathered, False if follow-up is needed."
    )
    patient_case: PatientCase = Field(
        default_factory=PatientCase,
        description="Extracted clinical patient case state."
    )

    model_config = ConfigDict(from_attributes=True)


class PossibleCondition(BaseModel):
    """An individual possible clinical condition assessed by an LLM model."""
    name: str = Field(..., description="Standard clinical condition name (e.g., 'Migraine').")
    score: int = Field(
        ...,
        ge=1,
        le=100,
        description="AI assessment score (1-100). NOTE: Does NOT represent clinical probability."
    )
    supporting_factors: List[str] = Field(
        default_factory=list,
        description="Case evidence supporting this condition."
    )
    contradicting_factors: List[str] = Field(
        default_factory=list,
        description="Case evidence making this condition less likely."
    )

    model_config = ConfigDict(from_attributes=True)


class ModelAssessmentOutput(BaseModel):
    """Structured assessment returned independently by Model 1, Model 2, Model 3."""
    possible_conditions: List[PossibleCondition] = Field(
        default_factory=list,
        description="List of possible conditions identified."
    )
    severity: str = Field(
        default="moderate",
        description="'mild', 'moderate', 'severe', or 'critical'."
    )
    red_flags: List[str] = Field(
        default_factory=list,
        description="Acute warning signs or emergency flags."
    )
    recommended_specialty: str = Field(
        default="General Physician",
        description="Clinical specialty recommended for evaluation."
    )
    missing_information: List[str] = Field(
        default_factory=list,
        description="Diagnostic tests or examinations needed to confirm/rule out."
    )

    model_config = ConfigDict(from_attributes=True)


class ConsensusOutput(BaseModel):
    """Output computed deterministically by the Python Consensus Engine."""
    leading_condition: str = Field(..., description="Top consensus condition name.")
    model_agreement: str = Field(..., description="Agreement ratio string (e.g., '3/3', '2/3', '1/3', '2/2').")
    consensus_score: int = Field(..., ge=0, le=100, description="AI Consensus Score (0-100).")
    agreement_level: str = Field(..., description="'high', 'moderate', or 'low'.")
    disagreements: List[str] = Field(
        default_factory=list,
        description="List of specific condition disagreements between models."
    )
    models_available: int = Field(default=3, description="Number of models that successfully returned assessments.")
    condition_votes: Dict[str, int] = Field(
        default_factory=dict,
        description="Vote count mapped by normalized condition name."
    )

    model_config = ConfigDict(from_attributes=True)


class JudgeOutput(BaseModel):
    """Synthesized clinical summary from the AI Judge reasoning model."""
    synthesized_summary: str = Field(
        ...,
        description="Concise, objective evaluation explaining why leading conditions were considered."
    )
    agreement_explanation: str = Field(
        ...,
        description="Explanation of clinical consensus among models."
    )
    disagreement_explanation: Optional[str] = Field(
        default=None,
        description="Explanation of why certain models differed or alternative possibilities considered."
    )
    missing_information: List[str] = Field(
        default_factory=list,
        description="Key tests or history details recommended to resolve clinical uncertainty."
    )
    recommended_specialty: str = Field(
        default="General Physician",
        description="Most appropriate specialist referral."
    )
    recommended_next_step: str = Field(
        default="Consult a licensed healthcare provider for in-person examination.",
        description="Actionable next step for the patient."
    )

    model_config = ConfigDict(from_attributes=True)


class SafetyOutput(BaseModel):
    """Evaluation generated deterministically by the Independent Safety Engine."""
    severity: str = Field(
        ...,
        description="'LOW', 'MODERATE', 'HIGH', or 'EMERGENCY'."
    )
    red_flags: List[str] = Field(
        default_factory=list,
        description="List of detected emergency or acute symptoms."
    )
    safety_override: bool = Field(
        default=False,
        description="True if immediate emergency care overrides normal AI assessment."
    )
    recommended_action: str = Field(
        ...,
        description="Clinical triage guidance or emergency directive."
    )

    model_config = ConfigDict(from_attributes=True)


class FinalAssessmentOutput(BaseModel):
    """Consolidated HealthAssist Multi-LLM Assessment result."""
    possible_conditions: List[str] = Field(
        default_factory=list,
        description="Ranked list of possible conditions evaluated across models."
    )
    leading_condition: str = Field(..., description="Top consensus condition.")
    consensus_score: int = Field(..., description="AI Consensus Score (0-100).")
    model_agreement: str = Field(..., description="e.g., '3/3' or '2/3'.")
    agreement_level: str = Field(..., description="'high', 'moderate', or 'low'.")
    severity: str = Field(..., description="Overall clinical severity (LOW, MODERATE, HIGH, EMERGENCY).")
    red_flags: List[str] = Field(default_factory=list, description="All identified red flags.")
    recommended_specialty: str = Field(..., description="Recommended medical specialty.")
    explanation: str = Field(..., description="Synthesized clinical explanation from AI Judge.")
    recommended_next_step: str = Field(..., description="Actionable clinical guidance.")
    safety_override: bool = Field(default=False, description="Whether safety engine override is active.")
    safety_action: Optional[str] = Field(default=None, description="Urgent safety recommendation if overridden.")
    disagreements: List[str] = Field(default_factory=list, description="Model disagreements if any.")
    models_available: int = Field(default=3, description="Number of models participating in consensus.")
    model_assessments: Dict[str, ModelAssessmentOutput] = Field(
        default_factory=dict,
        description="Outputs from individual models (NVIDIA, Ollama, Model 3)."
    )
    disclaimer: str = Field(
        default=(
            "CLINICAL DISCLAIMER: This is an AI-assisted health assessment for health awareness and "
            "educational purposes only. It does NOT constitute a medical diagnosis or treatment plan. "
            "Model scores are assessment relevance indicators, not disease probabilities. "
            "Always seek the advice of a qualified healthcare provider."
        ),
        description="Mandatory health awareness disclaimer."
    )

    model_config = ConfigDict(from_attributes=True)
