import {
  User,
  VitalMetric,
  Medication,
  Allergy,
  AssessmentRecord,
  HealthcareProvider,
  UpcomingAppointment,
  ChatMessageItem,
} from '../types'

export const mockCurrentUser: User = {
  id: 1,
  email: 'john.doe@healthassist.ai',
  fullName: 'John Doe',
  role: 'patient',
  patientId: 'HA-8492-MED',
  phone: '+1 (555) 349-9201',
  bloodType: 'O-Positive (O+)',
  dateOfBirth: 'May 14, 1994',
  allergiesCount: 2,
  activePrescriptionsCount: 2,
}

export const mockVitals: VitalMetric[] = [
  {
    id: 'vital-1',
    title: 'Resting Heart Rate',
    value: '72',
    unit: 'bpm',
    status: 'normal',
    change: '-2 bpm vs last wk',
    trend: 'stable',
    updatedAt: '15 mins ago',
    iconName: 'Heart',
  },
  {
    id: 'vital-2',
    title: 'Blood Pressure',
    value: '120/80',
    unit: 'mmHg',
    status: 'normal',
    change: 'Optimal range',
    trend: 'stable',
    updatedAt: '2 hours ago',
    iconName: 'Activity',
  },
  {
    id: 'vital-3',
    title: 'Blood Oxygen (SpO2)',
    value: '98.5',
    unit: '%',
    status: 'normal',
    change: '+0.5% healthy',
    trend: 'up',
    updatedAt: '30 mins ago',
    iconName: 'Droplets',
  },
  {
    id: 'vital-4',
    title: 'Sleep Duration',
    value: '7.8',
    unit: 'hrs',
    status: 'normal',
    change: '+45m vs baseline',
    trend: 'up',
    updatedAt: 'Today 7:00 AM',
    iconName: 'Moon',
  },
  {
    id: 'vital-5',
    title: 'Fasting Blood Glucose',
    value: '94',
    unit: 'mg/dL',
    status: 'normal',
    change: 'In target range',
    trend: 'stable',
    updatedAt: 'Today 8:15 AM',
    iconName: 'Zap',
  },
  {
    id: 'vital-6',
    title: 'Body Temperature',
    value: '98.6',
    unit: '°F',
    status: 'normal',
    change: 'Afebrile (Normal)',
    trend: 'stable',
    updatedAt: '4 hours ago',
    iconName: 'Thermometer',
  },
]

export const mockAllergies: Allergy[] = [
  {
    id: 'all-1',
    substance: 'Penicillin / Amoxicillin',
    reaction: 'Urticaria (hives), respiratory bronchospasm',
    severity: 'severe',
  },
  {
    id: 'all-2',
    substance: 'Peanuts & Tree Nuts',
    reaction: 'Mild angioedema, facial flushing',
    severity: 'moderate',
  },
  {
    id: 'all-3',
    substance: 'Latex',
    reaction: 'Contact dermatitis, localized pruritus',
    severity: 'mild',
  },
]

export const mockMedications: Medication[] = [
  {
    id: 'med-1',
    name: 'Loratadine (Claritin)',
    dosage: '10 mg Oral Tablet',
    frequency: 'Once Daily (Morning with water)',
    prescribedBy: 'Dr. Sarah Jenkins',
    refillsRemaining: 3,
    active: true,
  },
  {
    id: 'med-2',
    name: 'Multivitamin & Zinc Complex',
    dosage: '1 Capsule',
    frequency: 'Once Daily with breakfast',
    prescribedBy: 'Over the counter',
    refillsRemaining: 5,
    active: true,
  },
  {
    id: 'med-3',
    name: 'Albuterol Sulfate Inhaler',
    dosage: '90 mcg/actuation',
    frequency: 'As needed (PRN) for exercise-induced bronchospasm',
    prescribedBy: 'Dr. Marcus Chen',
    refillsRemaining: 1,
    active: true,
  },
]

export const mockAssessmentHistory: AssessmentRecord[] = [
  {
    id: 'HA-2026-0818',
    symptoms: 'Mild fronto-temporal throbbing headache, bilateral nasal congestion, slight dry cough for 2 days.',
    triageLevel: 'non-urgent',
    aiSummary:
      'Clinical presentation is consistent with mild viral upper respiratory tract infection / seasonal allergic rhinitis. No acute red flags observed.',
    differentialDiagnoses: [
      {
        name: 'Viral Rhinosinusitis',
        probability: 74,
        description: 'Benign upper respiratory infection with mild sinus congestion and localized pressure.',
      },
      {
        name: 'Seasonal Allergic Exacerbation',
        probability: 21,
        description: 'Allergen-mediated histamine response involving nasal mucosa.',
      },
      {
        name: 'Tension-Type Headache',
        probability: 5,
        description: 'Mild secondary tension headache aggravated by sinus pressure.',
      },
    ],
    consensusScore: 98.4,
    modelVotes: {
      geminiMed: 99.1,
      medPalm: 98.2,
      clinicalGpt: 97.9,
    },
    recommendedAction:
      'Supportive home care, hydration (2-3L/day), warm saline nasal rinses, and monitor temperature.',
    recommendedSpecialist: 'Family Medicine / Tele-Triage',
    createdAt: 'Aug 18, 2026 • 09:14 AM',
    status: 'resolved',
    duration: '2 days',
    reportedPainScale: 3,
    emergencyRedFlags: [
      'No stiff neck or photophobia',
      'No high fever (> 101.5°F)',
      'No dyspnea / shortness of breath',
    ],
    selfCareAdvice: [
      'Maintain oral fluid intake (electrolytes and herbal teas).',
      'Over-the-counter acetaminophen 500mg if headache intensifies (avoid penicillin products).',
      'Rest in an elevated position to facilitate sinus drainage.',
    ],
  },
  {
    id: 'HA-2026-0814',
    symptoms: 'Lower lumbar muscular soreness and mild spasms after high-intensity deadlift training.',
    triageLevel: 'self-care',
    aiSummary:
      'Localized acute paraspinal myofascial strain. Negative for radiculopathy, numbness, or saddle anesthesia.',
    differentialDiagnoses: [
      {
        name: 'Acute Lumbar Muscular Strain',
        probability: 91,
        description: 'Micro-tear of paraspinal lumbar muscles secondary to mechanical exertion.',
      },
      {
        name: 'Facet Joint Arthralgia',
        probability: 9,
        description: 'Transient localized axial irritation without nerve root impingement.',
      },
    ],
    consensusScore: 96.2,
    modelVotes: {
      geminiMed: 97.0,
      medPalm: 96.0,
      clinicalGpt: 95.6,
    },
    recommendedAction:
      'Relative rest for 48 hours, alternating ice/heat packs, gentle hamstring mobility stretches.',
    recommendedSpecialist: 'Physical Therapy / Sports Medicine',
    createdAt: 'Aug 14, 2026 • 06:45 PM',
    status: 'resolved',
    duration: '1 day',
    reportedPainScale: 4,
    emergencyRedFlags: [
      'No radiating leg pain below the knee',
      'No bowel or bladder dysfunction',
      'No motor weakness in toes or ankles',
    ],
    selfCareAdvice: [
      'Apply ice packs for 15-20 minutes every 3-4 hours for first 48 hours.',
      'Perform gentle pelvic tilts and avoid heavy lifting.',
      'Consult a clinician if symptoms do not improve within 7 days.',
    ],
  },
  {
    id: 'HA-2026-0722',
    symptoms: 'Mild erythematous contact rash on dorsal aspect of right forearm following gardening.',
    triageLevel: 'non-urgent',
    aiSummary:
      'Focal contact dermatitis likely triggered by plant resin or outdoor brush. No systemic signs.',
    differentialDiagnoses: [
      {
        name: 'Phytodermatitis / Contact Dermatitis',
        probability: 86,
        description: 'Exogenous chemical or plant antigen induced superficial skin irritation.',
      },
      {
        name: 'Allergic Urticaria',
        probability: 14,
        description: 'Localized histamine release in cutaneous tissue.',
      },
    ],
    consensusScore: 95.8,
    modelVotes: {
      geminiMed: 96.2,
      medPalm: 95.5,
      clinicalGpt: 95.7,
    },
    recommendedAction:
      'Wash area with gentle soap and water, apply 1% hydrocortisone cream twice daily, keep skin cool.',
    recommendedSpecialist: 'Dermatology & Skin Telehealth',
    createdAt: 'Jul 22, 2026 • 03:20 PM',
    status: 'resolved',
    duration: '12 hours',
    reportedPainScale: 2,
    emergencyRedFlags: [
      'No facial swelling or lip edema',
      'No warm spreading cellulitis border',
      'No purulent drainage or fever',
    ],
    selfCareAdvice: [
      'Keep affected limb cool and avoid direct sun exposure.',
      'Avoid scratching to prevent secondary bacterial infection.',
    ],
  },
]

export const mockProviders: HealthcareProvider[] = [
  {
    id: 1,
    name: 'Dr. Sarah Jenkins, MD',
    title: 'Attending Physician, Internal & Family Medicine',
    specialty: 'Family Medicine',
    hospital: 'Metro Health Telemedicine Network',
    rating: 4.92,
    reviewsCount: 218,
    availability: 'Available Today (Slots at 2:00 PM, 3:30 PM)',
    experienceYears: 14,
    initials: 'SJ',
    acceptingNewPatients: true,
    languages: ['English', 'Spanish'],
    telehealthFee: '$45 (Covered by Insurance)',
    nextSlots: ['Today 2:00 PM', 'Today 3:30 PM', 'Tomorrow 10:00 AM', 'Tomorrow 1:15 PM'],
  },
  {
    id: 2,
    name: 'Dr. Marcus Chen, MD, FACC',
    title: 'Senior Clinical Cardiologist & Preventive Care',
    specialty: 'Cardiology',
    hospital: 'Cardiovascular Care Specialists Institute',
    rating: 4.97,
    reviewsCount: 340,
    availability: 'Tomorrow 10:00 AM',
    experienceYears: 18,
    initials: 'MC',
    acceptingNewPatients: true,
    languages: ['English', 'Mandarin'],
    telehealthFee: '$65 (Covered by Insurance)',
    nextSlots: ['Tomorrow 10:00 AM', 'Tomorrow 11:30 AM', 'Friday 2:00 PM'],
  },
  {
    id: 3,
    name: 'Dr. Elena Rostova, MD',
    title: 'Board Certified Dermatologist & Telederm Specialist',
    specialty: 'Dermatology',
    hospital: 'Advanced Skin & Allergy Institute',
    rating: 4.88,
    reviewsCount: 175,
    availability: 'Available Today (Slot at 4:30 PM)',
    experienceYears: 11,
    initials: 'ER',
    acceptingNewPatients: true,
    languages: ['English', 'Russian', 'French'],
    telehealthFee: '$50 (Covered by Insurance)',
    nextSlots: ['Today 4:30 PM', 'Tomorrow 9:15 AM', 'Thursday 1:00 PM'],
  },
  {
    id: 4,
    name: 'Dr. David Kim, DO',
    title: 'Neurologist & Headache Medicine Fellow',
    specialty: 'Neurology',
    hospital: 'Neurological Sciences Telehealth Center',
    rating: 4.85,
    reviewsCount: 142,
    availability: 'Friday 11:15 AM',
    experienceYears: 9,
    initials: 'DK',
    acceptingNewPatients: false,
    languages: ['English', 'Korean'],
    telehealthFee: '$70 (Covered by Insurance)',
    nextSlots: ['Friday 11:15 AM', 'Next Mon 3:00 PM'],
  },
  {
    id: 5,
    name: 'Dr. Maya Patel, MD, MPH',
    title: 'Pulmonary & Respiratory Care Specialist',
    specialty: 'Pulmonology',
    hospital: 'Apex Telehealth Respiratory Network',
    rating: 4.95,
    reviewsCount: 198,
    availability: 'Available Today (Slot at 5:15 PM)',
    experienceYears: 16,
    initials: 'MP',
    acceptingNewPatients: true,
    languages: ['English', 'Hindi', 'Gujarati'],
    telehealthFee: '$55 (Covered by Insurance)',
    nextSlots: ['Today 5:15 PM', 'Tomorrow 2:00 PM', 'Friday 9:30 AM'],
  },
  {
    id: 6,
    name: 'Dr. Alexander Wright, MD',
    title: 'Orthopedic & Sports Medicine Consultant',
    specialty: 'Orthopedics',
    hospital: 'Pacific Musculoskeletal Institute',
    rating: 4.89,
    reviewsCount: 164,
    availability: 'Thursday 10:30 AM',
    experienceYears: 13,
    initials: 'AW',
    acceptingNewPatients: true,
    languages: ['English'],
    telehealthFee: '$60 (Covered by Insurance)',
    nextSlots: ['Thursday 10:30 AM', 'Friday 1:30 PM', 'Next Mon 11:00 AM'],
  },
]

export const mockAppointments: UpcomingAppointment[] = [
  {
    id: 'apt-1',
    providerName: 'Dr. Sarah Jenkins, MD',
    specialty: 'Family Medicine & Tele-Triage',
    hospital: 'Metro Health Telemedicine Network',
    date: 'Tomorrow, Aug 20, 2026',
    time: '02:00 PM EST',
    type: 'video',
    meetingLink: 'https://telehealth.healthassist.ai/room/med-8492-sj',
  },
  {
    id: 'apt-2',
    providerName: 'Dr. Marcus Chen, MD, FACC',
    specialty: 'Cardiology Review',
    hospital: 'Cardiovascular Care Specialists',
    date: 'Tuesday, Aug 25, 2026',
    time: '10:00 AM EST',
    type: 'video',
    meetingLink: 'https://telehealth.healthassist.ai/room/med-8492-mc',
  },
]

export const mockInitialChatMessages: ChatMessageItem[] = [
  {
    id: 'msg-1',
    sender: 'bot',
    text: "Hello John! I'm your HealthAssist Clinical AI Triage Assistant. I am backed by our Multi-LLM Clinical Consensus Protocol to assist you with symptom evaluation.",
    timestamp: 'Just now',
  },
  {
    id: 'msg-2',
    sender: 'bot',
    text: 'What primary symptoms or health concerns are you experiencing today?',
    timestamp: 'Just now',
    options: [
      { id: 'opt-1', label: '🤕 Headache & Congestion', value: 'I have a headache with nasal congestion' },
      { id: 'opt-2', label: '🫁 Cough & Sore Throat', value: 'I have a dry cough and a sore throat' },
      { id: 'opt-3', label: '⚡ Lower Back Pain', value: 'I have sharp pain in my lower back' },
      { id: 'opt-4', label: '🤢 Nausea & Stomach Upset', value: 'I am experiencing nausea and stomach cramps' },
      { id: 'opt-5', label: '🩹 Skin Rash or Itch', value: 'I have an itchy red rash on my arm' },
    ],
  },
]

export const mockTriageScenarioResult: AssessmentRecord = {
  id: 'HA-2026-0819-LIVE',
  symptoms: 'Mild fronto-temporal headache with nasal stuffiness and slight fatigue for 2 days. Pain rated 3/10.',
  triageLevel: 'non-urgent',
  aiSummary:
    'Consensus indicates acute benign viral rhinitis with mild secondary tension discomfort. Patient vitals remain stable without red flag warnings.',
  differentialDiagnoses: [
    {
      name: 'Viral Rhinosinusitis (Common Cold)',
      probability: 76,
      description: 'Self-limiting viral upper respiratory tract congestion with mild headache.',
    },
    {
      name: 'Allergic Rhinitis Exacerbation',
      probability: 19,
      description: 'Histamine-mediated nasal and sinus mucosal edema.',
    },
    {
      name: 'Tension-Type Headache',
      probability: 5,
      description: 'Axial cranial muscle tension associated with sinus congestion.',
    },
  ],
  consensusScore: 98.7,
  modelVotes: {
    geminiMed: 99.2,
    medPalm: 98.6,
    clinicalGpt: 98.3,
  },
  recommendedAction:
    'Rest, hydration (2.5L/day), warm saline nasal flush, and over-the-counter non-penicillin analgesics as needed.',
  recommendedSpecialist: 'Family Medicine / Tele-Triage',
  createdAt: 'Just now',
  status: 'active',
  duration: '2 days',
  reportedPainScale: 3,
  emergencyRedFlags: [
    'No high fevers (> 101.5°F)',
    'No neck stiffness or photophobia',
    'No shortness of breath or chest tightness',
    'No neurological deficit or confusion',
  ],
  selfCareAdvice: [
    'Drink plentiful fluids (warm water, electrolytes, herbal broths).',
    'Use steam inhalation or saline nasal mist 2-3 times daily.',
    'Take Acetaminophen 500mg every 6 hours if discomfort persists (avoid penicillin compounds).',
    'If symptoms worsen beyond 5-7 days or fever develops, connect with a telehealth doctor.',
  ],
}
